
import static java.awt.Color.green;
import static java.awt.Color.red;
import static java.awt.Color.yellow;
import java.util.Random;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author phowe
 */
public class jogo extends javax.swing.JDialog {

    /**
     * Creates new form jogo
     */
    public jogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    String random;
    String jogada;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TESOURA = new javax.swing.JButton();
        Pedra = new javax.swing.JButton();
        PAPEL = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jogadafinal = new javax.swing.JLabel();
        jogadadobott = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bot = new javax.swing.JLabel();
        voce = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PedraPapelTesoura");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(700, 300));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha a sua jogada:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 0, 1100, 110);

        TESOURA.setBackground(new java.awt.Color(204, 255, 204));
        TESOURA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tesoura.png"))); // NOI18N
        TESOURA.setBorder(null);
        TESOURA.setBorderPainted(false);
        TESOURA.setContentAreaFilled(false);
        TESOURA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TESOURAActionPerformed(evt);
            }
        });
        jPanel1.add(TESOURA);
        TESOURA.setBounds(870, 100, 210, 200);

        Pedra.setBackground(new java.awt.Color(204, 255, 204));
        Pedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/rock.png"))); // NOI18N
        Pedra.setBorder(null);
        Pedra.setBorderPainted(false);
        Pedra.setContentAreaFilled(false);
        Pedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedraActionPerformed(evt);
            }
        });
        jPanel1.add(Pedra);
        Pedra.setBounds(250, 110, 230, 185);

        PAPEL.setBackground(new java.awt.Color(204, 255, 204));
        PAPEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/papel.png"))); // NOI18N
        PAPEL.setBorder(null);
        PAPEL.setBorderPainted(false);
        PAPEL.setContentAreaFilled(false);
        PAPEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAPELActionPerformed(evt);
            }
        });
        jPanel1.add(PAPEL);
        PAPEL.setBounds(580, 120, 200, 185);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel2.setText("Bot:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(950, 360, 140, 60);

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel3.setText("Você:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 360, 140, 60);

        jogadafinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/not-removebg-preview.png"))); // NOI18N
        jPanel1.add(jogadafinal);
        jogadafinal.setBounds(180, 420, 290, 260);

        jogadadobott.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/not-removebg-preview.png"))); // NOI18N
        jPanel1.add(jogadadobott);
        jogadadobott.setBounds(890, 420, 290, 260);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Street_Fighter_VS_logo.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(530, 420, 290, 260);

        bot.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(bot);
        bot.setBounds(1050, 370, 140, 40);

        voce.setBackground(new java.awt.Color(255, 102, 51));
        voce.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(voce);
        voce.setBounds(370, 370, 140, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TESOURAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TESOURAActionPerformed
        jogada = "tesoura";
        MudarImagem();
        JogadadoBot();
        ConfirmarVitoria();
    }//GEN-LAST:event_TESOURAActionPerformed

    private void PedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedraActionPerformed
        jogada = "pedra";
        MudarImagem();
        JogadadoBot();
        ConfirmarVitoria();
    }//GEN-LAST:event_PedraActionPerformed

    private void PAPELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAPELActionPerformed
        jogada = "papel";
        MudarImagem();
        JogadadoBot();
        ConfirmarVitoria();
    }//GEN-LAST:event_PAPELActionPerformed

    private void MudarImagem(){
        if(jogada=="tesoura"){
            jogadafinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tesoura.png")));
        }
        else if(jogada=="pedra"){
            jogadafinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/rock.png")));
        }
        else if(jogada=="papel"){
            jogadafinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/papel.png")));
        }
    }
    
    private void JogadadoBot(){
        
        String[] opcoes = {"pedra", "papel", "tesoura"};

        int idx = new Random().nextInt(opcoes.length);
        random = (opcoes[idx]);
        
        if(random=="tesoura"){
            jogadadobott.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tesoura.png")));
        }
        else if(random=="pedra"){
            jogadadobott.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/rock.png")));
        }
        else if(random=="papel"){
            jogadadobott.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/papel.png")));
        }
    }
    
    private void ConfirmarVitoria(){
        if(jogada == "papel" && random == "papel"){
            voce.setText("Empate");
            voce.setForeground(yellow);
            bot.setText("Empate");
            bot.setForeground(yellow);
        }
        else if(jogada == "papel" && random == "pedra"){
            voce.setText("Ganhou");
            voce.setForeground(green);
            bot.setText("Perdeu");
            bot.setForeground(red);
        }
        else if(jogada == "papel" && random == "tesoura"){
            voce.setText("Perdeu");
            voce.setForeground(red);
            bot.setText("Ganhou");
            bot.setForeground(green);
        }
        if(jogada == "pedra" && random == "pedra"){
            voce.setText("Empate");
            voce.setForeground(yellow);
            bot.setText("Empate");
            bot.setForeground(yellow);
        }
        else if(jogada == "pedra" && random == "papel"){
            voce.setText("Perdeu");
            voce.setForeground(red);
            bot.setText("Ganhou");
            bot.setForeground(green);
        }
        else if(jogada == "pedra" && random == "tesoura"){
            voce.setText("Ganhou");
            voce.setForeground(green);
            bot.setText("Perdeu");
            bot.setForeground(red);
        }
        if(jogada == "tesoura" && random == "tesoura"){
            voce.setText("Empate");
            voce.setForeground(yellow);
            bot.setText("Empate");
            bot.setForeground(yellow);
        }
        else if(jogada == "tesoura" && random == "papel"){
            voce.setText("Ganhou");
            voce.setForeground(green);
            bot.setText("Perdeu");
            bot.setForeground(red);
        }
        else if(jogada == "tesoura" && random == "pedra"){
            voce.setText("Perdeu");
            voce.setForeground(red);
            bot.setText("Ganhou");
            bot.setForeground(green);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jogo dialog = new jogo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PAPEL;
    private javax.swing.JButton Pedra;
    private javax.swing.JButton TESOURA;
    private javax.swing.JLabel bot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jogadadobott;
    private javax.swing.JLabel jogadafinal;
    private javax.swing.JLabel voce;
    // End of variables declaration//GEN-END:variables
}
